STORY_DRAFTS = [
    {
        "id": "peach-garden-oath",
        "title_zh": "桃园三结义",
        "title_en": "The Oath of the Peach Garden",
        "level": 1,
        "age_range": "5-8",
        "paragraphs": [
            "很久以前，涿县贴出榜文，盼望有人一起保护乡里。刘备读完榜文，心里想着百姓过安稳日子，不由得长叹。他明白，一个人的力量有限，若能找到志同道合的朋友，就能多做一点好事。",
            "张飞听见叹声，走来问原因。刘备说自己力量小，却想做有益的事。张飞很赞成，愿意拿出家中积蓄，招呼乡勇。他说，家里有粮有地方，可以先让愿意帮忙的人聚在一起。",
            "这时关羽也来到店里。他听见二人的心愿，觉得他们正直可靠，便坐下一起商量。三个人越谈越投合，都想扶危助困。关羽说，做大事先要守信用，也要懂得照顾弱小的人。",
            "张飞家后有一片桃园，桃花开得正好。第二天，他们在桃树下结为兄弟，约定同心协力，互相提醒，先想着百姓。桃花落在衣袖上，像给这个约定盖上温柔的印记。",
            "从此，刘备、关羽、张飞一起练习、准备、照看乡亲。遇到有人搬东西，他们去帮忙；听见老人担心，他们耐心安慰。桃园里的誓言像春风一样，告诉大家：真正的勇气，是和朋友一起守护善良。",
        ],
        "vocab": [
            {"word": "榜文", "meaning": "public notice", "example": "涿县贴出榜文。"},
            {"word": "乡里", "meaning": "hometown area", "example": "大家一起保护乡里。"},
            {"word": "积蓄", "meaning": "savings", "example": "张飞愿意拿出积蓄。"},
            {"word": "结为兄弟", "meaning": "to become sworn brothers", "example": "他们在桃树下结为兄弟。"},
            {"word": "同心协力", "meaning": "to work together with one heart", "example": "他们约定同心协力。"},
            {"word": "乡亲", "meaning": "neighbors from the same village", "example": "他们照看乡亲。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "刘备看到榜文后最想做什么？",
                "options": ["保护乡里", "去摘桃子", "独自旅行"],
                "answer": "保护乡里",
                "explanation": "正文说刘备想着让百姓过安稳日子。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "三个人在哪里结为兄弟？",
                "options": ["桃园", "江边", "城楼"],
                "answer": "桃园",
                "explanation": "张飞家后有桃园，他们在桃树下结为兄弟。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "这个故事最想告诉我们什么？",
                "options": ["朋友齐心能守护善良", "遇事只靠一个人", "不要听别人说话"],
                "answer": "朋友齐心能守护善良",
                "explanation": "三人约定同心协力，互相提醒，照看乡亲。",
            },
        ],
        "retell_prompt": "说说刘备、关羽、张飞为什么愿意结为兄弟。",
        "cover_focus": "three kind young heroes under blooming peach trees, making a gentle promise of friendship",
    },
    {
        "id": "three-heroes-vs-lubu",
        "title_zh": "三英齐心退吕布",
        "title_en": "Three Heroes Face Lyu Bu Together",
        "level": 2,
        "age_range": "5-8",
        "paragraphs": [
            "虎牢关前，许多人马排成队伍。吕布骑着高马来到关口，声音洪亮，大家都觉得他的气势很强，一时不知怎样应对。风把旗子吹得呼呼响，年轻的人更需要一个稳稳的榜样。",
            "张飞先稳住队形，上前大声提醒同伴不要慌。关羽看见机会，立刻从旁边配合。刘备也赶来，帮助两位兄弟照看前后。他们没有急着表现自己，而是先让身边的人放心。",
            "三个人没有争谁最厉害，而是看着彼此的位置。张飞负责牵住局面，关羽负责相助，刘备负责补上空处，队伍慢慢安定下来。有人看见他们互相点头，也跟着站稳脚步。",
            "吕布见三人齐心，难以占到上风，便转身退回关内。关前的人们这才松了一口气，也看见了合作的力量。原来遇到强大的对手时，整齐的心比响亮的话更有用。",
            "这一回没有人靠吵闹取胜。刘备、关羽、张飞用勇敢、配合和信任告诉大家：真正强大的队伍，心要站在一起。每个人做好自己的位置，朋友之间互相补足，困难就会小一些。",
        ],
        "vocab": [
            {"word": "虎牢关", "meaning": "Hulao Pass", "example": "虎牢关前有许多人马。"},
            {"word": "气势", "meaning": "strong presence", "example": "吕布的气势很强。"},
            {"word": "队形", "meaning": "formation", "example": "张飞先稳住队形。"},
            {"word": "配合", "meaning": "to cooperate", "example": "关羽从旁边配合。"},
            {"word": "齐心", "meaning": "with one heart", "example": "吕布见三人齐心。"},
            {"word": "信任", "meaning": "trust", "example": "他们用配合和信任面对困难。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "吕布来到虎牢关前时，大家觉得他怎样？",
                "options": ["气势很强", "非常害羞", "迷路了"],
                "answer": "气势很强",
                "explanation": "正文说大家觉得吕布的气势很强。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "刘备、关羽、张飞靠什么稳住局面？",
                "options": ["配合", "争吵", "睡觉"],
                "answer": "配合",
                "explanation": "他们看彼此位置，互相配合。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "故事里的强大队伍需要什么？",
                "options": ["心站在一起", "每个人只顾自己", "声音越大越好"],
                "answer": "心站在一起",
                "explanation": "结尾说真正强大的队伍，心要站在一起。",
            },
        ],
        "retell_prompt": "用自己的话说说三位兄弟怎样一起稳住虎牢关前的局面。",
        "cover_focus": "three friendly heroes standing together before an ancient pass with banners and calm teamwork",
    },
    {
        "id": "quench-thirst-plums",
        "title_zh": "望梅止渴",
        "title_en": "Quenching Thirst with Plums",
        "level": 1,
        "age_range": "5-8",
        "paragraphs": [
            "有一次，曹操带着队伍赶路。太阳很大，路又长，大家走得口渴，脚步也慢了下来。曹操看在眼里，知道大家需要鼓励。他先让队伍放慢一点，又提醒大家不要互相抱怨。",
            "他没有责备大家，而是指着前方说，前面好像有一片梅林，梅子又酸又甜，想到味道就会舒服些。大家听了，嘴里仿佛有了清凉的感觉。有人还笑着说，酸梅子的味道已经跑到舌尖上了。",
            "队伍重新打起精神，继续向前走。有人想着酸甜的梅子，有人想着快点找到水源，脚步渐渐稳了。大家开始互相照看，前面的人提醒后面的人跟上，后面的人也不再着急。",
            "过了一会儿，大家真的找到水源，可以安心休息。曹操用一个巧妙的想法，帮助大家把难走的一段路坚持过去。找到水以后，大家更明白，先稳住心，路就能一步一步走完。",
            "这个故事后来成了成语“望梅止渴”。它提醒我们，遇到困难时，温和的鼓励和清楚的目标，能让人多一分力量。当然，真正解决问题还要继续寻找办法，就像大家最后找到了水源。",
        ],
        "vocab": [
            {"word": "口渴", "meaning": "thirsty", "example": "大家走得口渴。"},
            {"word": "鼓励", "meaning": "encouragement", "example": "大家需要鼓励。"},
            {"word": "梅林", "meaning": "plum grove", "example": "前面好像有一片梅林。"},
            {"word": "酸甜", "meaning": "sour and sweet", "example": "梅子又酸又甜。"},
            {"word": "水源", "meaning": "water source", "example": "大家真的找到水源。"},
            {"word": "坚持", "meaning": "to keep going", "example": "大家坚持走过难路。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "队伍一开始为什么慢了下来？",
                "options": ["大家口渴", "大家在唱歌", "大家找到梅子"],
                "answer": "大家口渴",
                "explanation": "正文说太阳大、路长，大家走得口渴。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "曹操用什么想法鼓励大家？",
                "options": ["前面有梅林", "天上会下雪", "马上回家"],
                "answer": "前面有梅林",
                "explanation": "曹操让大家想到酸甜的梅子。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "“望梅止渴”提醒我们遇到困难时可以怎样？",
                "options": ["用目标鼓励自己", "马上放弃", "责备同伴"],
                "answer": "用目标鼓励自己",
                "explanation": "故事说温和的鼓励和清楚的目标能带来力量。",
            },
        ],
        "retell_prompt": "说说曹操怎样用梅子的想象帮助大家继续赶路。",
        "cover_focus": "a traveling group imagining a bright plum grove ahead under a warm sun",
    },
    {
        "id": "three-visits-cottage",
        "title_zh": "三顾茅庐",
        "title_en": "Three Visits to the Thatched Cottage",
        "level": 1,
        "age_range": "5-8",
        "paragraphs": [
            "刘备听说隆中有位诸葛亮，读书多，主意好，心里十分敬佩。他想请诸葛亮一起帮助百姓，便带着关羽、张飞去拜访。山路弯弯，草木安静，刘备一路上都在想怎样把来意说清楚。",
            "第一次到茅庐，诸葛亮不在家。刘备没有生气，只留下问候。第二次再去，还是没有见到。张飞有些着急，刘备却说，请教贤人要有耐心。关羽也点点头，提醒大家说话要轻，脚步要稳。",
            "第三次，三人又来到茅庐。刘备先在门外等候，怕打扰主人休息。等诸葛亮醒来，他才恭恭敬敬地说明来意。他没有催促，也没有摆架子，只把心里的愿望认真讲出来。",
            "诸葛亮看见刘备这样尊重别人，也愿意认真交谈。他们谈到天下百姓，谈到怎样让更多人过安稳日子，越谈越投合。屋外风吹竹叶，屋里的人却越说越明白。",
            "后来，诸葛亮决定帮助刘备。三顾茅庐的故事告诉我们，真诚不是一句话，而是一次又一次有礼貌地坚持。想请别人帮助时，先学会尊重别人，也学会把目标说得清清楚楚。",
        ],
        "vocab": [
            {"word": "隆中", "meaning": "Longzhong, a place name", "example": "刘备听说隆中有位诸葛亮。"},
            {"word": "茅庐", "meaning": "thatched cottage", "example": "第一次到茅庐。"},
            {"word": "拜访", "meaning": "to visit respectfully", "example": "刘备去拜访诸葛亮。"},
            {"word": "耐心", "meaning": "patience", "example": "请教贤人要有耐心。"},
            {"word": "尊重", "meaning": "respect", "example": "诸葛亮看见刘备尊重别人。"},
            {"word": "真诚", "meaning": "sincerity", "example": "真诚需要有礼貌地坚持。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "刘备为什么去拜访诸葛亮？",
                "options": ["想请他帮助百姓", "想买草鞋", "想找桃花"],
                "answer": "想请他帮助百姓",
                "explanation": "正文说刘备想请诸葛亮一起帮助百姓。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "前两次没见到诸葛亮，刘备怎样做？",
                "options": ["继续有耐心", "立刻发火", "再也不来"],
                "answer": "继续有耐心",
                "explanation": "刘备说请教贤人要有耐心。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "三顾茅庐最能表现刘备的什么品质？",
                "options": ["真诚和尊重", "骄傲和粗心", "害怕和懒惰"],
                "answer": "真诚和尊重",
                "explanation": "刘备多次拜访，并在门外等候，表现真诚和尊重。",
            },
        ],
        "retell_prompt": "说说刘备三次拜访诸葛亮时怎样表现出真诚。",
        "cover_focus": "a modest thatched cottage in green hills, with respectful visitors waiting quietly",
    },
    {
        "id": "zhaoyun-changban",
        "title_zh": "长坂坡上的守护",
        "title_en": "Zhao Yun's Rescue at Changban",
        "level": 2,
        "age_range": "5-8",
        "paragraphs": [
            "长坂坡上，许多百姓正在赶路。人多路窄，队伍一时被挤散。刘备听说家人没有跟上，心里很着急。他请大家先照看老人和孩子，不要因为担心就乱成一团。",
            "赵云知道后，立刻让自己冷静下来。他没有乱跑，而是沿着来路仔细寻找，一边问人，一边注意孩子可能经过的地方。有人指给他一个方向，他就记在心里，再继续向前。",
            "路上声音很多，尘土也多。赵云仍然记得自己的责任：先找到孩子，再把孩子平安送回。他把小主人护在怀里，慢慢穿过人群。遇到拥挤的地方，他就放慢脚步，先让旁人过去。",
            "终于，赵云回到刘备身边，把孩子交给他。刘备看见孩子平安，十分感动，也感谢赵云一路守护。周围的人也安静下来，知道只要彼此照应，就能走过乱糟糟的时刻。",
            "长坂坡的故事告诉我们，勇敢不只是快和猛。真正的勇敢，是在大家慌乱时保持冷静，记住要守护的人。越是紧急，越要先想清楚下一步，这样才能把重要的人安全带回。",
        ],
        "vocab": [
            {"word": "长坂坡", "meaning": "Changban slope", "example": "长坂坡上有许多百姓。"},
            {"word": "挤散", "meaning": "to be separated in a crowd", "example": "队伍一时被挤散。"},
            {"word": "冷静", "meaning": "calm", "example": "赵云让自己冷静下来。"},
            {"word": "寻找", "meaning": "to search", "example": "他沿着来路仔细寻找。"},
            {"word": "平安", "meaning": "safe", "example": "孩子平安回来了。"},
            {"word": "守护", "meaning": "to protect", "example": "赵云一路守护。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "长坂坡上发生了什么？",
                "options": ["队伍被挤散", "大家在种梅树", "城门打开了"],
                "answer": "队伍被挤散",
                "explanation": "正文说人多路窄，队伍一时被挤散。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "赵云寻找孩子时先让自己怎样？",
                "options": ["冷静下来", "大哭起来", "睡一会儿"],
                "answer": "冷静下来",
                "explanation": "赵云知道后，立刻让自己冷静下来。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "故事中真正的勇敢是什么？",
                "options": ["慌乱时保持冷静", "只顾自己跑得快", "把声音喊得最大"],
                "answer": "慌乱时保持冷静",
                "explanation": "结尾说真正的勇敢是在慌乱时保持冷静，记住守护的人。",
            },
        ],
        "retell_prompt": "说说赵云怎样在长坂坡上守护孩子。",
        "cover_focus": "a calm guardian carrying a child safely through a busy ancient road, no weapons shown",
    },
    {
        "id": "borrow-arrows-boats",
        "title_zh": "草船借箭",
        "title_en": "Borrowing Arrows with Straw Boats",
        "level": 2,
        "age_range": "5-8",
        "paragraphs": [
            "周瑜请诸葛亮在三天内准备十万枝箭。这个任务听起来很难，大家都替他担心。诸葛亮却很从容，只说到时候一定交上。他没有先解释很多，而是把需要的东西一件件记下来。",
            "他请鲁肃帮忙准备二十条草船，又在船上扎满草把。鲁肃虽然不明白原因，还是按约定帮忙。到了大雾很浓的清晨，江面白茫茫一片，远处几乎看不清。",
            "诸葛亮让草船慢慢靠近曹营，又让船上敲起鼓声。对岸的人看不清情况，只好向声音来的地方放出许多箭。草船排得整整齐齐，像安静的朋友一起完成任务。",
            "箭纷纷落在草把上，草船两边很快插满了箭。诸葛亮看时机差不多，就带着船队顺风回来。回来的路上，他还让船换个方向，好让两边都能装满。",
            "三天期限到了，箭如数送到。大家这才明白，诸葛亮靠的不是急躁，而是观察天气、准备周全和守住约定。一个好办法，常常来自细心观察，也来自朋友之间的信任。",
        ],
        "vocab": [
            {"word": "草船", "meaning": "straw-covered boat", "example": "鲁肃准备二十条草船。"},
            {"word": "草把", "meaning": "bundles of straw", "example": "船上扎满草把。"},
            {"word": "大雾", "meaning": "heavy fog", "example": "大雾很浓的清晨。"},
            {"word": "鼓声", "meaning": "drum sound", "example": "船上敲起鼓声。"},
            {"word": "从容", "meaning": "calm and unhurried", "example": "诸葛亮很从容。"},
            {"word": "约定", "meaning": "agreement", "example": "他守住约定。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "周瑜请诸葛亮准备什么？",
                "options": ["十万枝箭", "一篮梅子", "三间茅庐"],
                "answer": "十万枝箭",
                "explanation": "正文开头说周瑜请诸葛亮在三天内准备十万枝箭。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "诸葛亮利用了什么天气？",
                "options": ["大雾", "大雪", "彩虹"],
                "answer": "大雾",
                "explanation": "草船出发时，大雾很浓，远处看不清。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "诸葛亮成功的重要原因是什么？",
                "options": ["观察和准备", "乱发脾气", "忘记期限"],
                "answer": "观察和准备",
                "explanation": "结尾说他观察天气、准备周全，并守住约定。",
            },
        ],
        "retell_prompt": "说说诸葛亮怎样用草船和大雾完成约定。",
        "cover_focus": "straw-covered boats on a misty river with arrows stuck in straw bundles, calm and nonviolent",
    },
    {
        "id": "red-cliffs",
        "title_zh": "赤壁同心",
        "title_en": "Teamwork at Red Cliffs",
        "level": 3,
        "age_range": "5-8",
        "paragraphs": [
            "赤壁江边，曹操的船队很多，江面显得十分热闹。孙权和刘备一方人数较少，大家知道，只有合作，才可能想出好办法。江边百姓也盼着风浪早点过去，日子重新安定。",
            "周瑜负责安排船只，诸葛亮负责观察风向，黄盖负责传递信号。每个人做的事不同，目标却一样：保护百姓，让江边早日安定。他们反复核对时间，提醒同伴不要抢先行动。",
            "他们发现曹操的船连在一起，转身不太方便。夜里，东南风起，信号传来，江面出现明亮火光，曹操的船队一下子乱了阵脚。火光在故事里只是计策的信号，不是吓人的场面。",
            "孙刘两方没有追着吵闹，而是按计划守住江岸，帮助自己的人安全前进。曹操见形势不利，带着船队后退。大家把路让给需要离开的人，也把注意力放在照看队伍上。",
            "赤壁的故事很有名。它告诉我们，聪明不是一个人的表演，而是许多人看准时机、互相信任、一起完成重要的事。分工清楚、彼此相信，小队伍也能做成大事情。",
        ],
        "vocab": [
            {"word": "赤壁", "meaning": "Red Cliffs", "example": "赤壁江边船队很多。"},
            {"word": "合作", "meaning": "cooperation", "example": "只有合作才有好办法。"},
            {"word": "风向", "meaning": "wind direction", "example": "诸葛亮观察风向。"},
            {"word": "信号", "meaning": "signal", "example": "黄盖负责传递信号。"},
            {"word": "保护", "meaning": "to protect", "example": "目标是保护百姓。"},
            {"word": "时机", "meaning": "right timing", "example": "他们看准时机。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "孙权和刘备一方为什么需要合作？",
                "options": ["人数较少", "想办花会", "要修茅庐"],
                "answer": "人数较少",
                "explanation": "正文说他们人数较少，只有合作才可能想出好办法。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "诸葛亮负责观察什么？",
                "options": ["风向", "梅子", "桃花"],
                "answer": "风向",
                "explanation": "第二段说诸葛亮负责观察风向。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "赤壁故事强调聪明来自什么？",
                "options": ["互相信任和合作", "一个人表演", "谁声音最大"],
                "answer": "互相信任和合作",
                "explanation": "结尾说聪明是许多人看准时机、互相信任、一起完成重要的事。",
            },
        ],
        "retell_prompt": "说说赤壁江边的人们怎样分工合作。",
        "cover_focus": "warm river scene at Red Cliffs with bright signal lights, boats, teamwork, no scary fire",
    },
    {
        "id": "huarong-path",
        "title_zh": "华容道上的仁义",
        "title_en": "Mercy on Huarong Path",
        "level": 2,
        "age_range": "5-8",
        "paragraphs": [
            "赤壁之后，曹操带着疲惫的队伍来到华容道。小路泥泞，大家走得很慢。关羽早已在路口等候，心里也很不平静。他知道这里的选择很重要，不能只凭一时的情绪。",
            "关羽记得，过去自己遇到困难时，曹操曾经礼待过他。现在两人站在不同一边，可旧日恩情仍在心中。关羽一向重信用，所以更明白恩情二字的分量。",
            "曹操上前说明来意，希望能借路离开。关羽看着疲惫的人们，想到仁义二字，也想到做人要记得恩情。路边风很冷，大家都在等他的决定。",
            "最后，关羽决定放行。他知道这个选择需要承担责任，但他愿意守住心里的仁义，不让恩情被忘记。放行之后，他也准备回去说明原因，接受该有的责问。",
            "华容道上的故事告诉我们，真正的英雄不只看输赢，也看内心是否正直。记得别人给过的善意，也是一种勇敢。做选择时想一想良心，比只想赢更难，也更珍贵。",
        ],
        "vocab": [
            {"word": "华容道", "meaning": "Huarong Path", "example": "曹操来到华容道。"},
            {"word": "疲惫", "meaning": "tired", "example": "曹操带着疲惫的队伍。"},
            {"word": "礼待", "meaning": "to treat with courtesy", "example": "曹操曾经礼待过关羽。"},
            {"word": "恩情", "meaning": "kindness received", "example": "旧日恩情仍在心中。"},
            {"word": "仁义", "meaning": "kindness and righteousness", "example": "关羽想到仁义二字。"},
            {"word": "放行", "meaning": "to let pass", "example": "关羽决定放行。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "曹操的队伍来到哪里？",
                "options": ["华容道", "桃园", "隆中"],
                "answer": "华容道",
                "explanation": "正文第一句说曹操带着队伍来到华容道。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "关羽为什么想起曹操？",
                "options": ["曹操曾礼待过他", "曹操送他梅子", "曹操教他弹琴"],
                "answer": "曹操曾礼待过他",
                "explanation": "正文说曹操过去曾经礼待过关羽。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "关羽最后做了什么选择？",
                "options": ["决定放行", "马上睡觉", "去拜访茅庐"],
                "answer": "决定放行",
                "explanation": "第四段说关羽决定放行。",
            },
        ],
        "retell_prompt": "说说关羽为什么在华容道上选择放行。",
        "cover_focus": "a muddy mountain path with Guan Yu making a thoughtful merciful choice, gentle expressions",
    },
    {
        "id": "seven-captures",
        "title_zh": "七擒孟获",
        "title_en": "Winning Trust Seven Times",
        "level": 3,
        "age_range": "5-8",
        "paragraphs": [
            "诸葛亮来到南方，见到当地首领孟获。孟获勇敢，也很爱自己的百姓，可他一开始不相信诸葛亮的诚意。他担心家乡受委屈，所以总想亲自看个明白。",
            "诸葛亮没有只想让人害怕。他说，要让人真正信服，先要让对方明白自己的心。于是，每次孟获不服，他都放他回去再谈。旁人觉得奇怪，诸葛亮却说，心服比口服更重要。",
            "一次又一次，诸葛亮守信，也请队伍尊重当地百姓。孟获看见他们不抢东西，不欺负人，心里的疑问慢慢少了。有人送来水和食物，诸葛亮也让大家礼貌道谢。",
            "到了第七次，孟获终于明白，诸葛亮不是为了逞强，而是希望大家少争执、多安定。他认真表示愿意和好，也愿意一起照看南方的百姓。",
            "七擒孟获的故事告诉我们，宽容有时比强硬更有力量。让别人信服，靠的是守信、尊重和为百姓着想。当彼此都愿意好好说话，原来的距离就会慢慢变近。",
        ],
        "vocab": [
            {"word": "孟获", "meaning": "Meng Huo", "example": "诸葛亮见到孟获。"},
            {"word": "首领", "meaning": "leader", "example": "孟获是当地首领。"},
            {"word": "诚意", "meaning": "sincerity", "example": "他不相信诸葛亮的诚意。"},
            {"word": "信服", "meaning": "to be convinced", "example": "要让人真正信服。"},
            {"word": "守信", "meaning": "to keep one's word", "example": "诸葛亮守信。"},
            {"word": "宽容", "meaning": "tolerance", "example": "宽容有时更有力量。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "孟获一开始相信诸葛亮的诚意吗？",
                "options": ["不相信", "完全相信", "没有见过"],
                "answer": "不相信",
                "explanation": "第一段说孟获一开始不相信诸葛亮的诚意。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "诸葛亮怎样对待不服的孟获？",
                "options": ["放他回去再谈", "不再说话", "让他去摘梅子"],
                "answer": "放他回去再谈",
                "explanation": "正文说每次孟获不服，诸葛亮都放他回去再谈。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "这个故事认为让别人信服靠什么？",
                "options": ["守信和尊重", "吵得更大声", "只想逞强"],
                "answer": "守信和尊重",
                "explanation": "结尾说让别人信服，靠的是守信、尊重和为百姓着想。",
            },
        ],
        "retell_prompt": "说说诸葛亮怎样一步一步让孟获信服。",
        "cover_focus": "Zhuge Liang and Meng Huo speaking respectfully in a bright southern landscape",
    },
    {
        "id": "empty-fort",
        "title_zh": "空城计",
        "title_en": "The Empty Fort Strategy",
        "level": 3,
        "age_range": "5-8",
        "paragraphs": [
            "有一回，诸葛亮身边的人很少，却听说司马懿带着队伍来到城外。城里的人紧张起来，不知道该怎样办。有人想关门，有人想躲起来，大家都看着诸葛亮。",
            "诸葛亮先让大家安静。他打开城门，安排几个人在门口慢慢扫地，自己穿戴整齐，坐到城楼上弹琴。扫地的人也照着吩咐，一下一下地扫，不让手忙脚乱露出来。",
            "琴声从城楼上传出去，清清稳稳。司马懿远远看见城门大开，又听见诸葛亮这样沉着，心里开始仔细判断。他知道诸葛亮平时谨慎，不会随便做奇怪的事。",
            "他想，诸葛亮平日做事周全，现在如此安静，也许城中另有安排。为了谨慎，他决定先带队退去，再观察情况。城里的人仍按诸葛亮的安排站好，没有大声欢呼。",
            "等城外安静下来，大家才松了一口气。诸葛亮告诉他们，越是紧张，越要让心稳住。空城计靠的正是沉着和判断。遇到难题时，先稳住自己，才有机会想出办法。",
        ],
        "vocab": [
            {"word": "城外", "meaning": "outside the city", "example": "司马懿来到城外。"},
            {"word": "安静", "meaning": "quiet", "example": "诸葛亮先让大家安静。"},
            {"word": "城楼", "meaning": "city tower", "example": "他坐到城楼上弹琴。"},
            {"word": "琴声", "meaning": "sound of the qin", "example": "琴声从城楼上传出去。"},
            {"word": "沉着", "meaning": "calm under pressure", "example": "诸葛亮很沉着。"},
            {"word": "判断", "meaning": "judgment", "example": "空城计靠的是沉着和判断。"},
        ],
        "questions": [
            {
                "id": "q1",
                "type": "single_choice",
                "prompt": "诸葛亮听说谁来到城外？",
                "options": ["司马懿", "孟获", "张飞"],
                "answer": "司马懿",
                "explanation": "第一段说司马懿带着队伍来到城外。",
            },
            {
                "id": "q2",
                "type": "single_choice",
                "prompt": "诸葛亮在城楼上做什么？",
                "options": ["弹琴", "种梅树", "贴榜文"],
                "answer": "弹琴",
                "explanation": "第二段说诸葛亮坐到城楼上弹琴。",
            },
            {
                "id": "q3",
                "type": "single_choice",
                "prompt": "空城计主要靠什么？",
                "options": ["沉着和判断", "吵闹和着急", "忘记安排"],
                "answer": "沉着和判断",
                "explanation": "结尾说空城计靠的正是沉着和判断。",
            },
        ],
        "retell_prompt": "说说诸葛亮怎样用沉着的样子让司马懿退去。",
        "cover_focus": "Zhuge Liang calmly playing a qin on a city tower with open gates and quiet streets",
    },
]
